### ISSUE TITLE
AutoCopySelectionText.uc.js and timer

### ISSUE THREAD

**Issue by Orriky** [benzBrake/FirefoxCustomize#1]
Hi,
I'd like you consider an improvement for this useful script.
I'd prefer to copy the selected text only when the left mouse button is keep pressed for a specified time after you have selected your text.
You can set time to zero if you want the script works as it does now.

Thanks

**Comment by benzBrake** [comment]
Done, I don't use this script, may be has bugs.

**Comment by Orriky** [comment]
Thanks!!!

It's wonderful. 
Maybe it has some bugs as you said, however it's already more useful to me.

**Comment by Orriky** [comment]
I'd like also the autocopy will be available even in the input boxes, urlbar etc

**Comment by benzBrake** [comment]
Now available in the input boxes of webpace.
I think auto copy it's not suitable for urlbar. So i've not Integrated within this script.
I give you a demo sciprt for copy urlbar script as follow
```
if (location.href.startsWith('chrome://browser/content/browser.x')) {
    document.getElementById('urlbar-input').addEventListener('mouseup', function(e) {
        if (e.button == 0)  {
            var input = event.target;
            var gClipboardHelper = Components.classes['@mozilla.org/widget/clipboardhelper;1'].getService(Components.interfaces.nsIClipboardHelper);
            gClipboardHelper.copyString(input.value.substring(input.selectionStart, input.selectionEnd));
        }
    }, false);
}
```

**Comment by Orriky** [comment]
Thanks again,
great work.

Are you interested in making this script work again?
[https://gist.github.com/Griever/709653](url)
overwriteMiddleMousePaste.uc.js
```

// ==UserScript==
// @name           overwriteMiddleMousePaste.uc.js
// @namespace      http://d.hatena.ne.jp/Griever/
// @include        main
// ==/UserScript==

document.documentElement.addEventListener("click", function(event){
	if (event.button !== 1 || !gPrefService.getBoolPref('middlemouse.paste')) return;

	var localName = event.target.localName.toLowerCase();
	if ((localName === 'input' || localName === 'textarea' || localName === 'textbox') && 
			document.commandDispatcher.getControllerForCommand("cmd_paste") ){
		goDoCommand("cmd_paste");
		event.preventDefault();

}


```

Firefox doesn't overwrite the already selected text when you paste the clipboard content using middle click.
That's annoying to me.

**Comment by benzBrake** [comment]
Nope, uc script can not modified web page directly, need to load in framscript, you can refer to AutoCopySelectionText.uc.js
