### ISSUE TITLE
[Bug]: downloadPlus_ff98.uc.js过长链接会导致窗口过宽

### ISSUE THREAD

**Issue by laulguo** [benzBrake/FirefoxCustomize#11]
### 你在用什么浏览器

Firefox

### 浏览器版本号

108

### 你在用什么 UC 环境(引导器)

alice0775

### 哪个脚本有问题

downloadPlus_ff98.uc.js

### 脚本有什么问题？

过长链接会导致窗口过宽
![捕获](https://user-images.githubusercontent.com/38545281/208459312-ee640c49-fd48-48fb-9225-ca1bf28e96fa.JPG)
图为知网下载论文时的窗口

### 错误日志

```shell
无
```

**Comment by benzBrake** [comment]
https://github.com/benzBrake/Firefox-downloadPlus.uc.js/blob/main/downloadPlus_ff98.uc.js

我不是修过了吗

**Comment by laulguo** [comment]
> https://github.com/benzBrake/Firefox-downloadPlus.uc.js/blob/main/downloadPlus_ff98.uc.js
> 
> 我不是修过了吗

目前版本依然可以复现。。。知网的链接特别的长
https://docdown.cnki.net/docdown/fulltext/download?q=NP7oX%2BLD6jdCNfVk3NNhrm9MJp3d6yNDS%2Fvyi4YVgZN7fhcvBouWmO3Vx%2BeShqnzKUfj90ytNhGH3kWJSLkna9ZueT%2Bg2Jn9lSK00ZX6YVffFZLZ%2BydZrz6h7%2Foqh%2BPwzj%2B62IANa4BvH5DY5J6QGhneqGD62SchX6uCUSFWYVJbffV3b6ihxjQh9OeIG4DnhFqdYh6AyXmcxbYzWgOpdGdNCa7qJPY0OM61APQ%2F%2BBFdW5w5mt3r4VZN3b%2FCmXdhHI3O40qEqME28DIMF4J8x0pdgOPcFXqZvZB596ofFTJnjrJrY5IL537irSJogqQq%2BTwbmWPA0bbjUgi75si%2F3Nn23QRDOjSbfsKrOeM7zvntFNnlHaG%2BJsI%2Fq691xDfMnDy2%2B84rV%2By0qTafRpcGxbjYE8F0g2H8z7HKERRJLCuHQfGnkr3%2B1RxC7S%2FLVTdjEvyzYCz4cle7nvg7FCc2L%2BIVBcMnlQVGR0q1uUMnR%2FKV28RQcemnLBbfds9l8RxGCbXyJ1BGKXyxXW3QKhw4ou34js%2FdAKrSxYBzaSmMmGTisIaio4tYStSd9kCLg%2FS3&invoice=O5z5xogRKYuQzV%2B2Wtjex0pqqqk7cIANP15dPrrbvs3fEQ%2FazPMgLWfj18ikY%2BY2VXKZqNlqk6k2H7AxoM8docOrPSwGK7LG4YCjFl7tT483wVW94mmw8czBNNoxaUF0WnqFn9DkNFJ0s44ydFsH44ZiOvAKQueRu6yX4VTOGE0%3D
当然这个链接应该是不能直接用的

**Comment by benzBrake** [comment]
https://github.com/benzBrake/Firefox-downloadPlus.uc.js/blob/8c66b3b887d472b085f71344c61f0ab5be291cc1/downloadPlus_ff98.uc.js#L247-L251

源码里有对108限制宽度的，你确认更新了吗，我的108里确实没有复现问题，手动把链接通过开发者工具填进去也不会撑大
可以尝试清理一下缓存

**Comment by laulguo** [comment]
> https://github.com/benzBrake/Firefox-downloadPlus.uc.js/blob/8c66b3b887d472b085f71344c61f0ab5be291cc1/downloadPlus_ff98.uc.js#L247-L251
> 
> 源码里有对108限制宽度的，你确认更新了吗，我的108里确实没有复现问题，手动把链接通过开发者工具填进去也不会撑大 可以尝试清理一下缓存
> 
> 我的链接也很长
> 
> ```
> https://95riq-my.sharepoint.com/personal/soft001_95riq_onmicrosoft_com/_layouts/15/download.aspx?UniqueId=e43cd300-01e1-47f9-a80d-56638617013f&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvOTVyaXEtbXkuc2hhcmVwb2ludC5jb21ANDRhY2NiOWUtNGIwYi00YWE5LThmODAtOTRlZGQ0OWNmYWY5IiwiaXNzIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwIiwibmJmIjoiMTY3MTUyNTczNSIsImV4cCI6IjE2NzE1MjkzMzUiLCJlbmRwb2ludHVybCI6Ink4eUFaNDJrQkRpVTRLOG1iVzV4dTdqNmY3UWZrNVNrbzlHM2Q0My8xREU9IiwiZW5kcG9pbnR1cmxMZW5ndGgiOiIxNTgiLCJpc2xvb3BiYWNrIjoiVHJ1ZSIsImNpZCI6Ik56Z3lPVFU0TURNdE5HWTNNaTAwTVRBMUxUbG1PREF0TVRWa1pqbGpaRFU1TXpKbSIsInZlciI6Imhhc2hlZHByb29mdG9rZW4iLCJzaXRlaWQiOiJNamt5T1RVNU9EVXROR1U0TnkwME5qSmtMVGt5WVRjdE9EQTBOVEkyT1dNMVl6YzEiLCJhcHBfZGlzcGxheW5hbWUiOiJBMV9MaXN0IiwiZ2l2ZW5fbmFtZSI6IjAwMSIsImZhbWlseV9uYW1lIjoiU09GVCIsImFwcGlkIjoiYTcwNzFlYTktZmE2My00Y2YwLWFmYmYtMjQzY2I1MTgyNWMxIiwidGlkIjoiNDRhY2NiOWUtNGIwYi00YWE5LThmODAtOTRlZGQ0OWNmYWY5IiwidXBuIjoic29mdDAwMUA5NXJpcS5vbm1pY3Jvc29mdC5jb20iLCJwdWlkIjoiMTAwMzIwMDE1NENEOTY3QiIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfDEwMDMyMDAxNTRjZDk2N2JAbGl2ZS5jb20iLCJzY3AiOiJhbGxmaWxlcy53cml0ZSIsInR0IjoiMiIsInVzZVBlcnNpc3RlbnRDb29raWUiOm51bGwsImlwYWRkciI6IjIwLjE5MC4xNjAuMjUifQ.WmJ3UXdBMXdUVW5oTUY0VVFUcFlhaS9OM2N5bjVwTU9sRTRYZjJCWUdEVT0&ApiVersion=2.0
> ```

重新配置了一个配置就好了。。我也不知道发生了啥。。。。问题是解决了
