### ISSUE TITLE
[Bug]: dialog window 's length sometimes too long, need to be fixed

### ISSUE THREAD

**Issue by Bingjie-Huang** [benzBrake/FirefoxCustomize#12]
### What browser are you using?

Firefox

### Browser version

107.0.1

### What UC scripts loader are you using?

xiaoxiaoflood

### which script has  bug

downloadPlus_ff98.uc

### What's wrong with the script?

The length of windows sometimes too long, when the complete link name's length is long, as shown below
just wonder how to correct it, or even disable the complete link shown in dialog window

![图片](https://user-images.githubusercontent.com/11184437/211161540-04e89e4a-7d83-4ce2-a228-d72d523616c3.png)

### Error log

```shell
NA
```

**Comment by benzBrake** [comment]
https://github.com/benzBrake/Firefox-downloadPlus.uc.js/commit/56431dcd7cce98239d2f2e85f1cf306888be6926

**Comment by Bingjie-Huang** [comment]
fixed
