### ISSUE TITLE
[NEED HELP]: AutoCopySelectionText

### ISSUE THREAD

**Issue by Orriky** [benzBrake/FirefoxCustomize#13]
### 你在用什么浏览器

Firefox

### 浏览器版本号

110.0b7

### 你在用什么 UC 环境(引导器)

xiaoxiaoflood

### 有什么问题

Hi,
I'd like your script shows a popup when the text is copied into the clipboard

https://imgur.com/ifnUgrz

**Comment by Orriky** [comment]
Thanks!!!

**Comment by Orriky** [comment]
I don't know how much time you still intend to dedicate to this script, however I wanted to inform you that when I select a word with a double click on it and I keep the button pressed for the pre-established time for the copy, actually many times the word is not copied. This problem does not occur when I select the word by sliding the mouse over it and hold the button down for the preset time and instead it only occurs when I double click on the word and hold down the button for the preset time.

**Comment by benzBrake** [comment]
Actually I don't use this script. I try to fix the problem, I don't know if it solves your problem

**Comment by Orriky** [comment]
Wow, it seems perfect
Thanks!!!
