### ISSUE TITLE
[NEED HELP]: BookmarkOpt.uc能不能增加个双击地址栏不隐藏书签栏的开关？

### ISSUE THREAD

**Issue by kidzgy** [benzBrake/FirefoxCustomize#14]
### 你在用什么浏览器

Firefox

### 浏览器版本号

109

### 你在用什么 UC 环境(引导器)

alice0775

### 有什么问题

BookmarkOpt.uc很好用，但就是偶尔会双击地址栏误将书签栏隐藏掉了，能不能增加个about:config参数开关，双击地址栏不隐藏书签栏呢？
谢谢！

**Comment by jiayiming** [comment]
https://github.com/benzBrake/FirefoxCustomize/commit/59eee180299320b7809d876c4ca57ef83d6bb1e6  正好我想问 这个1.3.3是这个情况  回退了？

**Comment by kidzgy** [comment]
更新了1.3.4，添加了中键添加书签到此的功能，非常棒！但是有个瑕疵，就是如果中键点击的不是文件夹或书签工具栏，而是标签，那么触发的是打开标签并且添加书签到目标书签的后面，并且收缩书签列表。
原来在不启用脚本的时候，中键对着标签点，是保留书签展开列表并且打开标签。
我的建议是：只在文件夹或书签工具栏触发，中键对着标签点的时候不触发脚本功能，而是保留系统自带的[保持书签展开列表并打开书签]。

感谢大大辛苦维护！

**Comment by benzBrake** [comment]
> 只在文件夹或书签工具栏触发，中键对着标签点的时候不触发脚本功能，而是保留系统自带的[保持书签展开列表并打开书签]。

简单看了一下，并不能获取点击的是图标还是标签，不好搞

**Comment by kidzgy** [comment]
[abhere2@moztw.org.zip](https://github.com/benzBrake/FirefoxCustomize/files/10889036/abhere2%40moztw.org.zip)
FF52前的远古扩展Add Bookmark Here2可以实现这个功能，不知道能不能借鉴一下？
