### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by laulguo** [benzBrake/FirefoxCustomize#18]
### 你在用什么浏览器

Firefox

### 浏览器版本号

112.0 (64 位)

### 你在用什么 UC 环境(引导器)

其他

### 哪个脚本有问题

ucf_drag_mod.uc.js

### 脚本有什么问题？

脚本挂了

### 错误日志

```shell
引导器版本为https://github.com/benzBrake/FirefoxCustomize/tree/master/userChromeJS/Loader的版本
```

**Comment by benzBrake** [comment]
我113b3没问题啊，确认时最新版嘛？
浏览器内容工具箱有没有相关报错

**Comment by benzBrake** [comment]
> 

确实是被修复了，我定制版里的就是修好的，但是我忘记上传到 Github 了
