### ISSUE TITLE
[Bug]: Firefox built-in pages

### ISSUE THREAD

**Issue by Orriky** [benzBrake/FirefoxCustomize#22]
### What browser are you using?

Firefox

### Browser version

114.0b3 (64 bit)

### What UC scripts loader are you using?

alice0775

### which script has  bug

AutoCopySelectionText.uc.js

### What's wrong with the script?

Autocopy doesn't work on Firefox built-in pages.

I want to add a suggestion.
The copy success popup should appear when the timeout has expired. So that when the popup appears I can release the mouse button.

### Error log

```shell
none
```

**Comment by benzBrake** [comment]
Thanks for reporting, It was a stupid mistake

**Comment by Orriky** [comment]
Thanks, the bug is fixed
On this page **_about:support_** doesn't appear the popup, however the text is autocopied correctly.

Regarding the suggestion, I didn't explain myself well: I want the text copied after the timeout expires and not when I release the mouse button.

**Comment by benzBrake** [comment]
I have add the feature copy text without relase buton, you need to toggle `ACST_COPY_WITHOUT_RELEASE_KEY` to grue

**Comment by Orriky** [comment]
Thanks!!!

**Comment by Orriky** [comment]
I reopen this issue because I notice that if I toggle `ACST_COPY_WITHOUT_RELEASE_KEY` to true the selected text is always copied after the timeout expires even if the mouse button is not pressed.
