### ISSUE TITLE
README 两个链接错误

### ISSUE THREAD

**Issue by wordpure** [benzBrake/FirefoxCustomize#29]
1. userChromeJS - 脚本列表的 [autoPopup++](https://github.com/benzBrake/FirefoxCustomize/blob/master/userChromeJS/README.md#%E8%84%9A%E6%9C%AC%E5%88%97%E8%A1%A8) 链接错了，后缀从 `.js` 变成了 `.s`。

![图片](https://github.com/benzBrake/FirefoxCustomize/assets/68013962/3fdbbe12-5c26-4186-a737-d82a8ccd2420)

2. [扩展选项菜单](https://github.com/benzBrake/FirefoxCustomize/tree/master/userChromeJS/ExtensionsOptionsMenu) 的链接连到后面的文字了。

![图片](https://github.com/benzBrake/FirefoxCustomize/assets/68013962/90e55719-dd23-49db-bd98-07f0e8f500d2)

**Comment by wordpure** [comment]
顺带一提，大佬有没有兴趣统一下 usrchrome 配置项的前缀？感觉统一加上 `userChromeJS` 后续查找的时候会方便一些

![图片](https://github.com/benzBrake/FirefoxCustomize/assets/68013962/e5500b50-6869-4e63-b2c4-88cd59544b9d)

**Comment by benzBrake** [comment]
> 顺带一提，大佬有没有兴趣统一下 usrchrome 配置项的前缀？感觉统一加上 `userChromeJS` 后续查找的时候会方便一些
> 
> ![图片](https://private-user-images.githubusercontent.com/68013962/324534975-e5500b50-6869-4e63-b2c4-88cd59544b9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4Mzg4MjQsIm5iZiI6MTcxMzgzODUyNCwicGF0aCI6Ii82ODAxMzk2Mi8zMjQ1MzQ5NzUtZTU1MDBiNTAtNjg2OS00ZTYzLWIyYzQtODhjZDU5NTQ0YjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDAyMTUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3MzM1NjU1ZjYyMjZmOWQwZGIwNjQzMzdjYjM2ZWRmMTI5N2YyMzlmMGIzOTg3YTNjZDRkYzRhNzhiOTY5ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QSv-cRaT6JXMRzO_BkM4kUhnRVJ0on2eCVQq2E1W-TU)

前面两个没有 userChromeJS 开头是因为历史原因，最原始作者版本的时候就这样了

**Comment by wordpure** [comment]
> 前面两个没有 userChromeJS 开头是因为历史原因，最原始作者版本的时候就这样了

如果不麻烦的话，可以加个判断来实现向后兼容，规范统一点总是好的

**Comment by wordpure** [comment]
Markdown 里单纯的链接可以直接用尖括号包裹来着。

![图片](https://github.com/benzBrake/FirefoxCustomize/assets/68013962/9210b6ce-def5-453b-beec-505281148274)

![图片](https://github.com/benzBrake/FirefoxCustomize/assets/68013962/bf0e3273-5836-444e-839e-e8d9f6909f61)

**Comment by benzBrake** [comment]
> Markdown 里单纯的链接可以直接用尖括号包裹来着。
> 
> ![图片](https://private-user-images.githubusercontent.com/68013962/324720405-9210b6ce-def5-453b-beec-505281148274.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NTQ2NTMsIm5iZiI6MTcxMzg1NDM1MywicGF0aCI6Ii82ODAxMzk2Mi8zMjQ3MjA0MDUtOTIxMGI2Y2UtZGVmNS00NTNiLWJlZWMtNTA1MjgxMTQ4Mjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA2MzkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MDljYTIxOTNmMmIwMmVmYjc2ZTYwYmJlMmE0ZTllZDYzNDYzMDM4MjNiNzhmODVmOWMyZTZjMDlhMTlkZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X0_Pp_X3QKDTF7aa2MlRh7wqPZz1SU-HQpOsU76hWB4)
> 
> ![图片](https://private-user-images.githubusercontent.com/68013962/324719731-bf0e3273-5836-444e-839e-e8d9f6909f61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NTQ2NTMsIm5iZiI6MTcxMzg1NDM1MywicGF0aCI6Ii82ODAxMzk2Mi8zMjQ3MTk3MzEtYmYwZTMyNzMtNTgzNi00NDRlLTgzOWUtZThkOWY2OTA5ZjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA2MzkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NDhhN2RmZTEwODg2NTBkNDc5MzQxNDgxMjg4NDQ3ZWI0Y2ExNTA4YmE4ODc1ZmIyYmNlYjUzZTE4NDI5M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WEt2Hjrk0_1oidzBDjRF6YOYxcr-VoN6UVAj8BEpaYY)

我使用 Typora 编写的，具体 markdown 我不编辑的

**Comment by benzBrake** [comment]
> > 前面两个没有 userChromeJS 开头是因为历史原因，最原始作者版本的时候就这样了
> 
> 如果不麻烦的话，可以加个判断来实现向后兼容，规范统一点总是好的

历史遗留导致很多 prefs 都是存成 addMenu 开头的，如果别人有存为`addMenu`开头的情况下不好兼容读取

https://github.com/benzBrake/FirefoxCustomize/blob/620b4a158406b6477c934d96f05c2130bb13c899/userChromeJS/addMenuPlus/addMenuPlus_fx72.uc.js#L428-L431
