### ISSUE TITLE
saveUCJS.uc.js 

### ISSUE THREAD

**Issue by Endor8** [benzBrake/FirefoxCustomize#32]
Hi benzBrake

In your Script saveUCJS.uc.js
line 23 should be now:
var fu = ChromeUtils.importESModule('resource://gre/modules/FileUtils.sys.mjs');
or similar. Here it works in Firefox 125 and above.

the file: FileUtils.jsm not exist any more in Firefox.
All .jsm files have been removed or renamed to sys.mjs.
There no .jsm File left in Firefox.

Kind Regards
Endor

**Comment by benzBrake** [comment]
Actually `Cu.import('resource://gre/modules/FileUtils.jsm');` works in nightly 2024-04-30

**Comment by benzBrake** [comment]
the commit  e41d280bf8dd2a5dff8b43b739428dc920a939ba solve this issue
