### ISSUE TITLE
[Bug]: 启用TabPlus 无法左键&中键点击书签

### ISSUE THREAD

**Issue by Kinmfer** [benzBrake/FirefoxCustomize#33]
### What browser are you using?

Firefox

### Browser version

127beta

### What UC scripts loader are you using?

alice0775

### which script has  bug

TabPlus.uc.js

### What's wrong with the script?

和左键&中键点击书签冲突

### Error log

```shell
暂无
```

**Comment by speeed001** [comment]
330行下面加上 ，435行这个whereToOpenLink也要改成BrowserUtils.whereToOpenLink不然图片打不开
.replace('lazy.BrowserUtils.whereToOpenLink(aEvent, false, true);', 'window.BrowserUtils.whereToOpenLink(aEvent, false, true)')

**Comment by Kinmfer** [comment]
可以了，感谢各位大佬！
