### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by GoogleBeEvil** [benzBrake/FirefoxCustomize#35]
### What browser are you using?

Firefox

### Browser version

127

### What UC scripts loader are you using?

xiaoxiaoflood

### What's wrong with the script?

movablePanelUIButton 在127上面异常，表现为 当工具栏有>>(更多工具) 这个图标时 三道杠无论怎么拖，都会在>>左边

### Error log

```shell
jsval.XPIDatabase is undefined config.js:104:19
    <anonymous> config.js:104
    <anonymous> config.js:105


000-xiaoxiaoflood.uc.js
ReferenceError : AppConstants is not defined 000-xiaoxiaoflood.uc.js:124
```

**Comment by benzBrake** [comment]
000-xiaoxiaoflood.uc.js 可以删掉了，与目前脚本无关
新版 UC 环境没有 104 行 https://github.com/benzBrake/userChrome.js-Loader/blob/main/program/config.js，先更新一下

至于 movablePanelUIButton.uc.js 暂时没空看，过两天

**Comment by GoogleBeEvil** [comment]
> 000-xiaoxiaoflood.uc.js 可以删掉了，与目前脚本无关 新版 UC 环境没有 104 行 [https://github.com/benzBrake/userChrome.js-Loader/blob/main/program/config.js，先更新一下](https://github.com/benzBrake/userChrome.js-Loader/blob/main/program/config.js%EF%BC%8C%E5%85%88%E6%9B%B4%E6%96%B0%E4%B8%80%E4%B8%8B)
> 
> 至于 movablePanelUIButton.uc.js 暂时没空看，过两天

更了5-24打包的脚本000-xiaoxiaoflood.uc.js 不报错了，但是 >>还是和三道杠冲突 。重建配置后问题解决   ，排查中。

**Comment by GoogleBeEvil** [comment]
在任意一个工具栏图标上右键  隐藏到折叠菜单，出现>>后 ，三道杠永远不能在>>右边

**Comment by benzBrake** [comment]
忘记说一句了，000-xiaoxiaoflood.uc.js 已经整合到最新的 UC 环境里，更新到最新的就无需使用了

**Comment by benzBrake** [comment]
用了一下没问题啊
![示例](https://github.com/benzBrake/FirefoxCustomize/assets/11323774/e31162f3-3157-4445-a36b-0cbbf80a21d8)

**Comment by GoogleBeEvil** [comment]
> 用了一下没问题啊 ![示例](https://private-user-images.githubusercontent.com/11323774/343997248-e31162f3-3157-4445-a36b-0cbbf80a21d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1Njg2ODYsIm5iZiI6MTcxOTU2ODM4NiwicGF0aCI6Ii8xMTMyMzc3NC8zNDM5OTcyNDgtZTMxMTYyZjMtMzE1Ny00NDQ1LWEzNmItMGNiYmY4MGEyMWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDA5NTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0N2JlYjk5ZjkzOTI0YmQ2MWNmNzlhZDE0Njk1NzRlMmZlNGMyYzRkYjFhZDE4NWZhMTFmMDM4ZjdkMzczMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yVpKh4AllntfXLFkxr5D85fDp1BtPX14kgrrw1g5lj8)

额  我的意思是   三道杠不能挪到>>后边

**Comment by benzBrake** [comment]
> > 用了一下没问题啊 ![示例](https://private-user-images.githubusercontent.com/11323774/343997248-e31162f3-3157-4445-a36b-0cbbf80a21d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1Njg2ODYsIm5iZiI6MTcxOTU2ODM4NiwicGF0aCI6Ii8xMTMyMzc3NC8zNDM5OTcyNDgtZTMxMTYyZjMtMzE1Ny00NDQ1LWEzNmItMGNiYmY4MGEyMWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDA5NTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0N2JlYjk5ZjkzOTI0YmQ2MWNmNzlhZDE0Njk1NzRlMmZlNGMyYzRkYjFhZDE4NWZhMTFmMDM4ZjdkMzczMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yVpKh4AllntfXLFkxr5D85fDp1BtPX14kgrrw1g5lj8)
> 
> 额 我的意思是 三道杠不能挪到>>后边 另外 你最新的是哪版啊 我书签里的step by step 还是5-7号的 (https://github.com/benzBrake/FirefoxCustomize/blob/master/userChromeJS/README.md)

这个脚本就是让三道杠可以在>>前移动，你删掉这个脚本就是在后面

**Comment by GoogleBeEvil** [comment]
不能做成自由移动么  我印象里是能自由拖动，在>>前后都行的。难道是我记错了
