### ISSUE TITLE
[Bug]: 131.0b1已经失效了

### ISSUE THREAD

**Issue by dsyo2008** [benzBrake/FirefoxCustomize#40]
### 你在用什么浏览器

Firefox

### 浏览器版本号

131.0

### 你在用什么 UC 环境(引导器)

xiaoxiaoflood

### 哪个脚本有问题

BMMultiColumn.uc.js

### 脚本有什么问题？

脚本挂了

### 错误日志

```shell
开发版131已经失效了，请修复一下吧，谢谢
```

**Comment by benzBrake** [comment]
哪个脚本啊

**Comment by dsyo2008** [comment]
> 哪个脚本啊

忘了说脚本太尴尬，不好意思，是BMMultiColumn.uc.js
![图片](https://github.com/user-attachments/assets/61fd488a-42dc-4734-a180-1465edf1d04f)
看上去是失效，无法滚动，禁用这脚本后下滚动正常

**Comment by benzBrake** [comment]
131 中`flex-wrap: wrap` 不知道为什么没用，我暂时没空研究

**Comment by dsyo2008** [comment]
> 131 中`flex-wrap: wrap` 不知道为什么没用，我暂时没空研究

明白了，暂时禁用，等你有空研究吧

**Comment by benzBrake** [comment]
https://github.com/benzBrake/FirefoxCustomize/commit/5b10a605faf77790d2a55d0e96d79fa412f23155

修复了
