### ISSUE TITLE
[Bug]: BookmarkOpt.uc.js添加书签到此处无效

### ISSUE THREAD

**Issue by jiayiming** [benzBrake/FirefoxCustomize#8]
### 你在用什么浏览器

Firefox

### 浏览器版本号

107

### 你在用什么 UC 环境(引导器)

alice0775

### 脚本有什么问题？

在书签栏文件夹中右键-添加书签到此处无效，实际未添加书签。

### 错误日志

```shell
无任何错误日志
```

**Comment by benzBrake** [comment]
108b9 测试了书签工具栏和侧边栏都可以啊，而且我查了一下 api 没有变更啊

**Comment by jiayiming** [comment]
其实最近几个月一直有这个问题  不是107的变动。。

**Comment by benzBrake** [comment]
太神奇了，本来就是个 BUG，但是触发率很低很低，但是用了这个脚本把触发率提高到 95%

**Comment by jiayiming** [comment]
已经欧克了
